---
# tasks file for aussielunix.powerdns-admin

- name: include assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: include tasks for installing powerdns
  ansible.builtin.import_tasks: powerdns_install.yml

- name: include tasks for powerdns post install
  ansible.builtin.import_tasks: powerdns_post.yml
