---
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install required packages in Redhat derivatives
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ pdns_admin_packages }}"
  when: ansible_os_family == 'RedHat'

- name: Install required packages in Debian derivatives
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - "{{ pdns_admin_packages }}"
  when: ansible_os_family == 'Debian'

- name: Create "{{ pdns_admin_root_path }}" directory
  file:
    path: "{{ pdns_admin_root_path }}"
    state: directory

- name: Git clone PowerDNS Admin
  git:
    repo: "{{ pdns_admin_git_repo_url }}"
    dest: "{{ pdns_admin_path }}"

- name: Install virtualenv
  pip:
    name: virtualenv

- name: PIP install requirements for PowerDNS Admin
  pip:
    requirements: "{{ pdns_admin_requirements_path }}"
    virtualenv: "{{ pdns_admin_python_venv_path }}"

- name: Install some more required packages
  pip:
    name: "{{ item }}"
    virtualenv: "{{ pdns_admin_python_venv_path }}"
  with_items: "{{ pdns_admin_pip_packages }}"
